name: p_4
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.19.0-146.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hydrated_bloc: ^9.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_webrtc: ^0.9.34
  permission_handler: ^11.0.1
  image_picker: ^1.0.0
  uuid: ^4.2.1
  file_picker: ^8.1.2
  open_file: ^3.3.2
  path_provider: ^2.0.15
  http: ^1.2.0
  mime: ^1.0.4
  record: ^5.0.4
  audioplayers: ^6.1.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  get_it: ^7.6.0
  easy_localization: ^3.0.7
  # socket_io_client: ^2.0.2
  # video_player: ^2.4.0
  # flutter_ringtone_player: ^3.2.0
  # flutter_vibrate: ^1.3.0
  supabase_flutter: ^2.3.3
  intl: ^0.19.0
  emoji_picker_flutter: ^3.0.0
  flick_video_player: ^0.9.0
  videosdk: ^1.1.3
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.2
  flutter_osm_plugin: ^1.3.0
  location: ^6.0.2
  geocode: ^1.0.3
  lottie: ^3.0.0
  photo_manager: ^3.0.0-dev.2
  photo_view: ^0.15.0
  url_launcher: ^6.1.11
  contacts_service: ^0.6.3
  shared_preferences: ^2.2.0
  scrollview_observer: ^1.16.5
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  video_thumbnail: ^0.5.3
  internet_connection_checker: ^2.0.0
  swipe_to: ^1.0.2
  webview_flutter: ^4.2.2
  flutter_screen_lock: ^9.0.2
  photo_manager_image_provider: ^2.1.0
  latlong2: ^0.9.0
  flutter_map: ^7.0.2
  timeago: ^3.6.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  wechat_assets_picker: ^9.2.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo/logo1.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/localization/
    - assets/localization/en-US.json
    - assets/localization/fa-IR.json
    - assets/image/logo/
    - assets/image/
    - assets/lottie/lock.json
    - assets/lottie/start_conversition.json

  fonts:
    - family: header
      fonts:
        - asset: assets/font/Arabic.ttf

    - family: body
      fonts:
        - asset: assets/font/Iranian Sans.ttf
