name: p_4
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  socket_io_client: ^2.0.2
  hydrated_bloc: ^9.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_webrtc: ^0.9.34
  permission_handler: ^10.4.2
  image_picker: ^1.0.0
  uuid: ^3.0.7
  file_picker: ^5.2.10
  open_file: ^3.3.2
  path_provider: ^2.0.15
  http: ^0.13.5
  mime: ^1.0.4
  record: ^4.4.4
  audioplayers: ^4.1.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  get_it: ^7.6.0
  easy_localization: ^3.0.3
  loading_animation_widget: ^1.2.0+4
  supabase_flutter: ^1.10.10
  intl: ^0.17.0
  emoji_picker_flutter: ^1.6.1
  # video_player: ^2.4.0
  flutter_typeahead: ^3.2.7
  flick_video_player: ^0.4.0
  videosdk: ^1.1.3
  # flutter_ringtone_player: ^3.2.0
  # flutter_vibrate: ^1.3.0
  flutter_local_notifications: ^15.1.1
  timezone: ^0.9.2
  # geocoding: ^2.0.0
  flutter_osm_plugin: ^0.53.2
  location: ^4.4.0
  # geocoder_buddy: ^1.0.1
  geocode: ^1.0.3
  lottie: ^2.3.2
  photo_manager: ^2.7.1
  image_painter: ^0.5.0
  photo_view: ^0.14.0
  url_launcher: ^6.1.11
  contacts_service: ^0.6.3
  shared_preferences: ^2.2.0
  flutter_screen_lock: ^9.0.1
  local_auth: ^2.1.6
  scrollview_observer: ^1.16.5
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  video_thumbnail: ^0.5.3
  internet_connection_checker: ^1.0.0+1
  

dev_dependencies:
  flutter_test: 
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/audios/
    - assets/lottie/
    - assets/localization/
    - assets/localization/en-US.json
    - assets/localization/fa-IR.json
    - assets/image/logo/
    - assets/image/
    - assets/lottie/lock.json
    - assets/lottie/start_conversition.json
    - assets/audio_wave_forms/test.json

  fonts:
    - family: header
      fonts:
        - asset: assets/font/Arabic.ttf

    - family: body
      fonts:
        - asset: assets/font/Iranian Sans.ttf
